Repository APLA-Toolbox/PythonPDDL, pull requests merged in 2020-12, with the labels that each got.

#1 Add base
  .github/workflows/pyapp.yml
  .gitignore
  data/.gitkeep
  main.py
  src/__init__.py
  src/modules.py
  src/pddl.py
Labels: enhancement

#4 Integrate CI/CD
  .github/workflows/pyapp.yml
  .gitignore
  data/domain.pddl
  data/problem.pddl
  main.py
  requirements.txt
  src/modules.py
  src/pddl.py
  src/state.py
  tests/test_pddl.py
Labels: enhancement

#15 Update README.md
  README.md
Labels: documentation

#16 Improve planners architecture
  .github/workflows/pyapp.yml
  codecov.yml
  main.py
  src/astar.py
  src/automated_planner.py
  src/bfs.py
  src/dfs.py
  src/dijkstra.py
  src/heuristics.py
  src/node.py
  src/pddl.py
  src/state.py
  tests/test_automated_planner.py
  tests/test_pddl.py
Labels: architecture, enhancement

#18 Separate build and test
  .github/workflows/build.yml
  .github/workflows/tests.yml
  README.md
  src/astar.py
  src/automated_planner.py
  src/bfs.py
  src/dfs.py
  src/dijkstra.py
  src/node.py
  tests/test_automated_planner.py
Labels: ci

#19 Add codecov flag
  .github/workflows/tests.yml
Labels: ci

#23 Remove UI flag
  src/automated_planner.py
Labels: enhancement

#29 Add basic heuristic
  src/automated_planner.py
  src/heuristics.py
  tests/test_automated_planner.py
  tests/test_heuristics.py
Labels: enhancement

#35 Improve devops
  .github/workflows/format.yml
Labels: ci, devops, enhancement

#36 formatter now commits to master when a MR is merged
  .github/workflows/format.yml
Labels: ci, devops

#37 revert changes
  .github/workflows/format.yml
  src/automated_planner.py
  src/heuristics.py
  tests/test_automated_planner.py
  tests/test_heuristics.py
Labels: ci, devops

#47 Create CONTRIBUTING.md
  docs/CONTRIBUTING.md
Labels: documentation

#46 Create CODE_OF_CONDUCT.md
  docs/CODE_OF_CONDUCT.md
Labels: documentation

#48 Update issue templates
  .github/ISSUE_TEMPLATE/bug_report.md
  .github/ISSUE_TEMPLATE/feature_request.md
Labels: devops, documentation

#55 Packaging Pypi
  .github/workflows/build.yml
  .github/workflows/tests.yml
  README.md
  jupyddl/__init__.py
  jupyddl/a_star.py
  jupyddl/automated_planner.py
  jupyddl/bfs.py
  jupyddl/dfs.py
  jupyddl/dijkstra.py
  jupyddl/heuristics.py
  jupyddl/node.py
  setup.py
  src/__init__.py
  tests/test_automated_planner.py
Labels: ci, devops

#56 [Critical Fix] Broken package
  .github/workflows/tests.yml
  main.py
  setup.py
  tests/test_astar.py
  tests/test_automated_planner.py
  tests/test_heuristics.py
Labels: bug, ci

#57 Fix logger bug
  jupyddl/automated_planner.py
  setup.py
Labels: bug

#59 Data Analyst
  .gitignore
  jupyddl/a_star.py
  jupyddl/automated_planner.py
  jupyddl/bfs.py
  jupyddl/data_analyst.py
  jupyddl/dfs.py
  jupyddl/dijkstra.py
  jupyddl/node.py
  requirements.txt
  setup.py
  tests/test_astar.py
  tests/test_data_analyst.py
Labels: enhancement, performance

#60 Bump to v0.3.0
  jupyddl/__init__.py
  setup.py
Labels: devops

#67 Resolve issues 63 61 65
  .github/workflows/format.yml
  README.md
  jupyddl/automated_planner.py
  jupyddl/data_analyst.py
Labels: architecture, devops, documentation, enhancement

#71 Add Heuristics comparing plot
  README.md
  jupyddl/data_analyst.py
  tests/test_data_analyst.py
Labels: enhancement

#74 Add pddl examples limit
  README.md
  jupyddl/data_analyst.py
  tests/test_data_analyst.py
Labels: architecture

#62 Improve coverage on search algorithms #20
  tests/test_dfs.py
  tests/test_main.py
  tests/test_search.py
Labels: enhancement

#78 Fix pddl path in test
  .gitignore
  tests/test_search.py
Labels: bug
