Repository APLA-Toolbox/PythonPDDL, pull requests merged in 2021-01, with the labels that each got.

#58 Overload __str__ #53
  jupyddl/automated_planner.py
  jupyddl/node.py
  tests/test_dfs.py
  tests/test_node.py
Labels: enhancement

#84 Bump to 0.4.0
  README.md
  setup.py
Labels: devops

#86 add success stats
  jupyddl/data_analyst.py
  tests/test_data_analyst.py
Labels: enhancement

#88 Greedy best first
  jupyddl/automated_planner.py
  jupyddl/data_analyst.py
  jupyddl/greedy_best_first.py
  jupyddl/heuristics.py
  tests/test_data_analyst.py
  tests/test_greedy_best_first.py
Labels: enhancement

#91 Implement scalable metrics object
  .gitignore
  jupyddl/a_star.py
  jupyddl/automated_planner.py
  jupyddl/bfs.py
  jupyddl/data_analyst.py
  jupyddl/dfs.py
  jupyddl/dijkstra.py
  jupyddl/greedy_best_first.py
  jupyddl/heuristics.py
  jupyddl/metrics.py
  jupyddl/node.py
  scripts/ipc.py
  tests/test_automated_planner.py
  tests/test_basic_astar.py
  tests/test_basic_search.py
  tests/test_data_analyst.py
  tests/test_dfs.py
  tests/test_greedy_best_first.py
  tests/test_metrics.py
Labels: architecture, enhancement
